version: "3.5"

services:


  ##### NODEJS #####
  nodesandbox_node:
    image: sandbox/node:${NODE_VERSION}
    container_name: "${COMPOSE_PROJECT_NAME}_node"
    build:
      context: .
      dockerfile: ./DockerfileNode
      args:
        NODE_VERSION: ${NODE_VERSION}
    volumes:
      - ../:/app
      - /app/node_modules
    stdin_open: true